employee/urls.py
employee/views.py
follow_control_card/utils.py
follow_control_home/templates/follow_control_base.html
follow_control_home/views.py

-Add logout
-Add create card when user loggin

Fix create follow/control/ create new cards

---

client/templates/base_client.html
client/templates/index_client.html
client/templates/partials/client_list.html
client/views.py

added htmx for client

---

budget/templates/catalog/catalog_edit.html
budget/templates/catalog/catalog_list.html
budget/templates/catalog/catalog_list_element.html
budget/views.py

-Separate list and element list in catalog

Fix catalog item edit

---

employee/views.py
follow_control_card/templates/partials/edit-task-form.html
follow_control_card/templates/tasks/task.html

-Fix the bugs in htmx for the Apps to Budgets,Tarjet,Employee. 
-Fix the error that caused the created login to replace the previus login. 
-All good with the sidebars.

Hotfixed User & Htmx

---

alya/settings.py
logistic_inventory/forms.py
logistic_inventory/models.py
logistic_inventory/views.py
logistic_inventory_api/urls.py

-Create QR and save for each new item

Add qr to item

---

.gitignore
accounting_order_sales/templates/base_accounting.html
accounting_order_sales/templates/requirements/requirement_order_detail.html
accounting_order_sales/templates/requirements/requirement_order_list.html
accounting_order_sales/urls.py
accounting_order_sales/views.py
alya/settings.py
logistic_requirements/models.py
logistic_requirements/templates/requirement_order_detail.html
logistic_requirements/templates/requirement_order_list.html
logistic_requirements/views.py

- Add new field in logisctic_requirements model - state 
- Import templates logistic app to accounting_order_sales
- Import views logistic app to accounting_order_sales

Add field in accounting_order_sales/requirements

---

employee/models.py
employee/templates/base_employee.html
employee/templates/registration/register.html
employee_portal/forms.py
employee_portal/templates/base_portal.html
employee_portal/templates/change_password.html
employee_portal/templates/confirm_password_change.html
employee_portal/templates/edit_portal.html
employee_portal/templates/index_portal.html
employee_portal/urls.py
employee_portal/views.py
hub/templates/partials/cards.html

- Add CRUD in my user's
- Add templates edit, index, confirm password, change password
- Add views in user app
- Change name 'index_portal' to 'profile'
- Add urls in user's app
- Add Forms in user's app

Add Functions in 'My Accounts(Employee_Portal)'

---

employee/forms.py
employee/templates/edit/edit_supervisor.html
employee/templates/edit/edit_technician.html
employee/templates/list/list_supervisor.html
employee/templates/list/list_technician.html
employee/templates/registration/register.html
employee/urls.py
employee/views.py

- Add new templates edit
- Add function edit for supervisor & technician
- Add button redirect to FormEdit
- Fix auto escale form registration.

Add Functions Edit in Employee App

---

.env
accounting_order_sales/templates/requirements/requirement_order_list.html
budget/templates/index_budget.html
employee/views.py

- Add libraries js datatables Accounting_O_S & budget
- Fix messages change role employee App

Add datatables JS

---

logistic_requirements/views.py
project/templates/partials/project_list.html
project/templates/project_base.html
project/templates/project_index.html
project/views.py

- Add function get_queryset
- Add new table for import SaleOrder dependecy the Project assing
- Add model prefetch import of django.db.models
- Delete hx-post in project_index.html

Add get_queryset for Project-Sales Order

---

accounting_order_sales/models.py
alya/settings.py
project/templates/partials/project_list.html
project/templates/partials/sales_order_detail.html
project/urls.py
project/views.py

- Add tables with detail for each project
- Add new functions in PucharseOrder & SalesOrder
- Add new template for details for each project
- Add new url/view for redirect new template
- Go into more details for Accounting_O_S

Add more Functions in Project App

---

requests/templates/requests/my_requests.html
requests/templates/requests/requirement_order_preview.html
requests/urls.py
requests/views.py

- Add new template requirements_O_P.html.
- Add new urls.
- Add new view.

Add new function in Requests App

---

accounting_order_sales/templates/base_accounting.html
accounting_sunat/admin.py
accounting_sunat/apps.py
accounting_sunat/forms.py
accounting_sunat/models.py
accounting_sunat/templates/cargar_pdf.html
accounting_sunat/templates/combined_template.html
accounting_sunat/templates/crear_cronograma.html
accounting_sunat/templates/detalle_resolucion.html
accounting_sunat/templates/mostrar_datos.html
accounting_sunat/templates/pagos_cronograma.html
accounting_sunat/templates/resolucion_list.html
accounting_sunat/templates/semaforo.html
accounting_sunat/templates/ver_cronogramas.html
accounting_sunat/templates/ver_pagos_cronograma.html
accounting_sunat/templates/ver_todos_los_cronogramas.html
accounting_sunat/tests.py
accounting_sunat/urls.py
accounting_sunat/views.py
alya/settings.py
alya/urls.py

- Add new models to cronogramas
- Add new views & forms
- Add new templates to SUNAT

Add SUNAT APP to accounting_O_S

---

budget_commercial/templates/commercial_budget/delete_commercial_budget.html
budget_commercial/templates/commercial_budget/detail_commercial_budget.html
budget_commercial/templates/index_budget_commercial.html
budget_commercial/templates/partials/_budget_commercial_form.html
budget_commercial/templates/partials/_budget_commercial_table.html
budget_commercial/urls.py
budget_commercial/views.py

- Add templates delete & detail - commecial_budget.html
- Add partials forms & tables - budget_commercial.html
- Add new urls for budget commerial
- Add new views delete & detail

Add views for budget commercial

---

alya/settings.py
budget/forms.py
budget/models.py
budget/templates/index_budget.html
budget_commercial/templates/index_budget_commercial.html

- Fix DATABASE in brach newdevelop
- Changes in forms.py
- Changes models budget_servicetime & quantity
- Fix width in templates of budget/budget_commercial

Changes in Budget App

---

accounting_order_sales/forms.py
accounting_order_sales/templates/salesorder/salesorder-edit.html
accounting_order_sales/templates/salesorder/salesorder-form.html
accounting_order_sales/templates/salesorder/salesorder-list.html
accounting_order_sales/views.py
requests/views.py

-Only see request if order sales is active

Add active option in order sales

---

follow_control_card/forms.py
follow_control_card/urls.py
follow_control_report/templates/dailyvaluation/daily_evaluation_card_list.html
follow_control_report/templates/dailyvaluation/daily_evaluation_cards.html
follow_control_report/urls.py
follow_control_report/views.py

- Create new form - CardForm
- Fix path "/" in urls.py
- Migrate table in the other template
- Add form for search & ID in table/daily_evaluation_card_list.html
- Add new urls
- Add new filter in daily_evaluation_card function
- Add search function

Fix Bugs  Follow Control Card App

---

follow_control_backlog/views.py

Aun falta pulirlo, según lo que querían era que se duplique sus tareas.

Fix function to replicate task list weekly

---

alya/settings.py
requests/forms.py
requests/views.py

- Add validations to avoid duplicate items
- Add validations to prevent creating order requests

Add new validations in Requests App

---

budget/forms.py
budget/models.py
budget/templates/budgetplus/budget_item_plus.html
budget/templates/budgetplus/budget_plus.html
budget/templates/partials/budget_item_plus_css.html
budget/utils.py
logistic_requirements/views.py

- Add new field in models.py in Budget App
- Add new fields coin in forms.py
- Add new fields in template fot budget_item_plus.html
- Add news columns in util.py bank and account

Add new changes in Budget App

---

accounting_order_sales/templates/requirements/requirement_order_detail.html
accounting_order_sales/templates/requirements/requirement_order_list.html

-Change Aprovar for Validar in accouting requiriments

Change names

---

accounting_order_sales/templates/base_accounting.html
accounting_order_sales/templates/logistic_requirements/logistic_index.html
accounting_order_sales/templates/logistic_requirements/logistic_list.html
accounting_order_sales/templates/requirements/requirement_order_detail.html
accounting_order_sales/templates/requirements/requirement_order_list.html
logistic_inventory/templates/base_logistic.html
logistic_requirements/templates/requirement_order_index.html
logistic_requirements/templates/requirement_order_list.html
logistic_requirements/templates/requirements_approved/requirement_order_approved_list.html
requests/templates/requests/my_requests.html
requests/templates/requests/requirement_order_preview.html
requests/templates/total_requests/all_requests.html

-Change from "Aprobado" to "Validado" in html.

Change all names in requirements

---

budget/templates/budgetplus/budget_only_detail_item_plus.html
budget/templates/budgetplus/budget_only_detail_plus.html
budget/templates/index_budget.html
budget/urls.py
budget/views_budget.py

- Add new template for restrict editing by user
- Add new urls
- Add new view

feat: budget plus - add new view, only reviewed

---

budget/views.py

Exclude igv in.
- SVT00060
- SVT00061
They're internal services and utility.

feat: Exclude igv in some items.

---

logistic_requirements/models.py

Add the next extesion in RequirementOrdenItem
- docx
- xlsx
- csv

feat: add extensions support

---

project_finance/admin.py
project_finance/models.py
project_finance/urls.py
project_finance/utils.py

Creating documentation for legacy code maintenance
Reviewed-by: Mick

refactor: Project Finance App - documenting code

---

budget/admin.py
budget/apps.py
budget/forms.py
budget/models.py
budget/urls.py
budget/utils.py
budget/views.py
budget/views_budget.py

Add parameters and returns sections in all functions in budget / python files.

docs: In app budget update docstring.

---

requests/templates/index_requests.html
requests/templates/requests/my_requests.html
requests/templates/total_requests/all_requests.html
requests/views.py

Sort request to reverse
